### ISSUE TITLE
ci: `auto-deploy.yml`에 OIDC 토큰 관련 코드 추가

### ISSUE THREAD

**Issue by KOKEONHO** [YouCanOrder/YouCanOrder-Server#7]
AWS 인증을 `auto-deploy.yml`에서 OIDC로 인증하기 위해 ID Token 관련 코드 추가

```yaml
permissions:
  id-token: write
  contents: read
```
